print("Dieses Programm schreibt eine Kurzgeschichte in der Sie vorkommen")

name = input("Wie lautet Ihr Vorname? ")
geburtstag = input("In welchem Monat ist Ihr Geburtstag? ")
haarfarbe = input("Ihre Haarfarbe: ")
wohnort = input("Ihr Wohnort: ")

print()
print("Die Verabredung mit dem Komissar")
print()
print("Es war ein grauer Morgen im " + geburtstag + ".")
print("Die Sonne war gerade erst aufgegangen und es war noch wenig Betrieb im Stadtzentrum von " + wohnort + ".")
print("Hauptkommissar " + name + " stand vor dem Bistro und schaute auf die Uhr.")
print("Wo bleibt Stefan nur?, dachte er. Ist etwas schiefgelaufen?")
print("Vielleicht hatte Stefans Freundin Wind von der Sache bekommen und seine Pläne durchkreuzt.")
print("Eine Person mit struwweligen " + haarfarbe + "en Haaren näherte sich mit raschen Schritten.")
print("Der Kommissar atmete auf, als er den Menschen erkannte. Es war Stefan.")
print("Jetzt konnte eigentlich nichts mehr schiefgehen ...")
input()
